version: '3.8'

services:
  clockit-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      - CLOCKIT_DATA_DIR=/app/data
      - PYTHONPATH=/app
    volumes:
      - clockit_data:/app/data
      - clockit_logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # PostgreSQL database for cloud storage option
  clockit-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=clockit
      - POSTGRES_USER=clockit
      - POSTGRES_PASSWORD=clockit_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose for development/debugging only
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clockit -d clockit"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  clockit_data:
    driver: local
  clockit_logs:
    driver: local
  postgres_data:
    driver: local