apiVersion: apps/v1
kind: Deployment
metadata:
  name: clockit-app
  labels:
    app: clockit
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clockit
  template:
    metadata:
      labels:
        app: clockit
        version: v1
    spec:
      containers:
      - name: clockit
        image: clockit:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: DATABASE_TYPE
          value: "postgres"
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: clockit-secrets
              key: postgres-host
        - name: POSTGRES_DB
          value: "clockit"
        - name: POSTGRES_USER
          value: "clockit"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clockit-secrets
              key: postgres-password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: clockit-secrets
              key: secret-key
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /app/data
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: clockit-data-pvc
      - name: logs
        emptyDir: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000