apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clockit-data-pvc
  labels:
    app: clockit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and specify storage class if needed
  # storageClassName: fast-ssd