name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run tests
        env:
          DEV_MODE: sqlite
          ENVIRONMENT: test
        run: |
          . .venv/bin/activate
          PYTHONPATH=${{ github.workspace }} .venv/bin/pytest -q

      - name: Run linters
        run: |
          . .venv/bin/activate
          pip install black isort flake8
          black --check .
          isort --check-only .
          flake8
